module.exports = {
    // SERVER
    SERVER_LOOP_TIME: 1000/30,

    // ROOM
    FIELD_SIZE: 14142,
    FOOD_COUNT: 100,

    // PLAYER
    PLAYER_MIN_CELL_COUNT: 16,
    PLAYER_MAX_DUAL_COUNT: 2,
    PLAYER_VIEW_SCALE: 0.3,
    PLAYER_VIEW_SIZE: 700,
    PLAYER_REMERGE_TIME: 100,
    PLAYER_START_MASS: 5000,
    PLAYER_SPLIT_POSITION: 50,
    PLAYER_SPLIT_DISTANCE: 780,
    PLAYER_COLLISION_DETECT_TIME: 15,

    // CELL
    CELL_MIN_MASS: 30,
    CELL_MAX_MASS: 22500,
    CELL_EAT_RATE: 1.25,
    
    // EJECT
    EJECT_MASS: 13,
    EJECT_SHOT_POSITION: 20,
}