module.exports = {
    // SERVER
    SERVER_LOOP_TIME: 1000/30,
    MESSAGE_MAX_LENGTH: 256,

    // ROOM
    FIELD_SIZE: 14142,
    FOOD_COUNT: 100,
    FOOD_SIZE: 20,
    LEADERBOARD_MAX: 10,
    CHAT_RETRANSMISSION_TIME: 3000,
    CHAT_MAX_HISTORY: 10,

    // PLAYER
    PLAYER_TEAM_MAX_LENGTH: 10,
    PLAYER_NAME_MAX_LENGTH: 10,
    PLAYER_MIN_CELL_COUNT: 16,
    PLAYER_MAX_DUAL_COUNT: 2,
    PLAYER_DUAL_CAMERA: 1, // 0 -> change | 1 -> center
    PLAYER_VIEW_SCALE: 0.3,
    PLAYER_VIEW_SIZE: 700,
    PLAYER_REMERGE_TIME: 100,
    PLAYER_START_MASS: 5000,
    PLAYER_SPLIT_POSITION: 50,
    PLAYER_SPLIT_DISTANCE: 780,
    PLAYER_COLLISION_DETECT_TIME: 15,
    PLAYER_CELL_DECAY: 0.998,

    // CELL
    CELL_MIN_MASS: 30,
    CELL_MAX_MASS: 22500,
    CELL_EAT_RATE: 1.25,
    
    // EJECT
    EJECT_MASS: 13,
    EJECT_SHOT_POSITION: 20,
}